### ISSUE TITLE
Unresolved identifiers issue

### ISSUE THREAD

**Issue by HarshitDaftary** [crossroadlabs/Express#18]
I faced following error while running HelloWorld example.

```
/home/ubuntu/Projects/Project7/Packages/ExecutionContext-0.3.1/ExecutionContext/ExecutionContext.swift:162:15: error: use of unresolved identifier 'time_t'
    let sec = time_t(timeout)
              ^~~~~~
/home/ubuntu/Projects/Project7/Packages/ExecutionContext-0.3.1/ExecutionContext/ExecutionContext.swift:164:16: error: use of unresolved identifier 'time spec'
    var time = timespec(tv_sec:sec, tv_nsec: nsec)
               ^~~~~~~~
/home/ubuntu/Projects/Project7/Packages/ExecutionContext-0.3.1/ExecutionContext/ExecutionContext.swift:166:5: error: use of unresolved identifier 'nano sleep'
    nanosleep(&time, nil)
    ^~~~~~~~~
<unknown>:0: error: build had 1 command failures
error: exit(1): ["/home/ubuntu/swift/swift2.2/usr/bin/swift-build-tool", "-f", "/home/ubuntu/Projects/Project7/.build/debug/ExecutionContext.o/llbuild.yaml"]
```

**Comment by ypopovych** [comment]
What Ubuntu and Swift versions are you use?
Seems as some problem with imports on some Swift version.

**Comment by HarshitDaftary** [comment]
I use following ubuntu version
Ubuntu 14.04.3 LTS

I use following Swift version
Swift version 2.2-dev

**Comment by ypopovych** [comment]
Swift revision?

**Comment by HarshitDaftary** [comment]
I did swift --version 

Swift version 2.2-dev (LLVM 3ebdbb2c7e, Clang f66c5bb67b, Swift 42591f7cba)
Target: x86_64-unknown-linux-gnu

Can you please suggest me how to get swift revision from terminal ?

**Comment by ypopovych** [comment]
Express works only on two latest development snapshots of Swift. So, please, update your Swift to latest development snapshot (at this moment 2016-03-01-a.)

**Comment by HarshitDaftary** [comment]
Ok. Thanks I will download newer version.

**Comment by HarshitDaftary** [comment]
Is this correct version ?

Swift version 3.0-dev (LLVM b361b0fc05, Clang 11493b0f62, Swift fc261045a5)
Target: x86_64-unknown-linux-gnu

Because I am facing this error with it

error: NoSources("/home/ubuntu/Projects/Project7/Packages/TidyJSON-1.1.0/Tests/TestCases")

**Comment by ypopovych** [comment]
Yes.
Please read this instructions
https://github.com/crossroadlabs/Express/blob/master/doc/gettingstarted/buildrun.md

**Comment by HarshitDaftary** [comment]
It works perfectly. Thanks :+1:
