### ISSUE TITLE
Cannot build Express on Linux and MAC OS X using the latest Swift 2.2 or Swift 3.0 and SPM

### ISSUE THREAD

**Issue by ilap** [crossroadlabs/Express#20]
The express does not build on Linux nor Mac OS X using the latest Swift Development snapshots (2.2 or 3.0).
Also the SPM build does not work either with the provided Package.swift file.

**Comment by dileping** [comment]
@ilap Thanks for reporting! We are aware of the issue and already working on it.

The thing is that the latest snapshot is too far 3.0 and it's not possible to maintain compatibility with Swift 2.1.

The next version will drop support of Swift 2.1 and Xcode 7.2 and will be compatible with Swift 2.2 and Xcode 7.3 and the latest Swift 3.0 snapshots.

Meanwhile, consider using Xcode 7.2 and Snapshot from March 2.

We hope to roll out a new version in a day or two. Thanks for understanding.

**Comment by ilap** [comment]
that's fine thx

**Comment by ilap** [comment]
Thank you.

**Comment by dileping** [comment]
Quick update here. We issued today a new minor release featuring compatibility with Xcode 7.3. For linux  you still have to use Swift DEV SNAPSHOT of 03.01.16.

Swift 3.0 will be supported in version 0.4. Stay tuned

**Comment by ilap** [comment]
Thank you, for the update.

**Comment by piyushchauhan2011** [comment]
Is minor release of `0.4x` with `Swift 3.x` compatibility going to be released soon ? @dileping

**Comment by dileping** [comment]
@piyushchauhan2011 Thanks for asking. Here is the update:

Implementing support of Swift 3.x is not a small task so we consider to add it in the next major release which is 0.4.

0.4 is going to be a dramatic improvement and we are almost there. The main feature is that it's based on brand new reactive foundation for Swift ([Reactive Swift](https://github.com/reactive-swift): ExecutionContext, Future, Event, Stream, etc.) which we are currently working on. The plan is to finish with Swift 3.x support there first (almost done), finish with Streams (half way there) and then we release brand new Express v0.4. The release most probably will be issued in August-September.

**Comment by piyushchauhan2011** [comment]
Cool, Thanks @dileping for the updates 👍  . Trying recently the framework, enjoying it.

**Comment by dileping** [comment]
@piyushchauhan2011 Cool, thanks for nice the words! Hope you'll enjoy v0.4.x even more ;)

If you have any issues, please, ask here or on stackoverflow with `swiftexpress` tag. Will try to help you.
