### ISSUE TITLE
Any idea about Nimble problem ? 

### ISSUE THREAD

**Issue by durul** [crossroadlabs/Express#22]
Hello Guys, 

I have tried tree different machine. I have always taken same error message below. 

brew install swift-express
==> Installing swift-express from crossroadlabs/tap
==> Cloning https://github.com/crossroadlabs/ExpressCommandLine.git
Updating /Library/Caches/Homebrew/swift-express--git
==> Checking out tag 0.2.1
==> carthage update --platform Mac
**Last 15 lines from /Users/duruldalkanat/Library/Logs/Homebrew/swift-express/01.carthage:
The following build commands failed:
    CompileSwift normal x86_64 /tmp/swift-express20160324-691-1jkr1m1/Carthage/Checkouts/Commandant/Carthage/Checkouts/Nimble/Nimble/Adapters/NimbleXCTestHandler.swift
    CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
(2 failures)**

**\* Fetching Regex
**\* Fetching Commandant
**\* Fetching Result
**\* Checking out Commandant at "0.8.3"
**\* Checking out SwiftTryCatch at "af21e8f91cd994a8ea459540f922f0e5e1c57618"
**\* Downloading Regex.framework binary at "v0.4.1: optional groups support"
**\* Downloading Result.framework binary at "1.0.2: A Swift Result"
**\* xcodebuild output can be found in /var/folders/nz/f5vmppwd7kg44qt1xsdk_b_m0000gn/T/carthage-xcodebuild.Fw3Nwo.log
**\* Building scheme "Commandant" in Commandant.xcworkspace
**\* Building scheme "Nimble-OSX" in Commandant.xcworkspace

**Comment by dileping** [comment]
Hi @durul ,

what version of Xcode do you currently use?

**Comment by durul** [comment]
Hello, I am using Xcode Version 7.3 (7D175). All O.S X and homebrew updated.

**Comment by dileping** [comment]
Yeah, the issue appeared since Xcode 7.3 release (and not only this issue). We are working on it now.

Meanwhile, if you have a machine with Xcode 7.2, it should work.
