### ISSUE TITLE
build dispatch failed issue for missing pthread_workqueue.h and its solution on Linux

### ISSUE THREAD

**Issue by learningpro** [crossroadlabs/Express#26]
On Ubuntu15.10, we also need another command to make a success on build dispatch
sudo apt-get install libpthread-workqueue-dev

and then ,build dispatch will succeed

Thanks

**Comment by dileping** [comment]
@learningpro Thanks for putting it here. Looks like Apple has got rid of internal libpwq dependency and moved to a shared library (good thing, btw, as we are using it as well in ExecutionContext).

Would you consider changing the docs, please? Help is highly appreciated as we are currently focused on new 0.4 release and don't want to loose concentration.

**Comment by learningpro** [comment]
@dileping  OK, I will try to make a PR, thanks for your hard working on 0.4 release and I cannot wait to see it ^_^

**Comment by dileping** [comment]
@learningpro Thanks a lot for kind words. We are pushing very hard toward the release. Your help is very appreciated. I answered you on the PR thread as well.

**Comment by learningpro** [comment]
I'm happy to make some contribution
