### ISSUE TITLE
Error on: swift-express init HelloExpress

### ISSUE THREAD

**Issue by KDReiners** [crossroadlabs/Express#3]
Hello,

I've tried getting started on El Capitain, but got this error after issuing swift-express init HelloExpress:

CompileSwift normal x86_64 /Users/kdreiners/HelloExpress/Carthage/Checkouts/Express/Express/Transaction.swift
    CompileSwift normal x86_64 /Users/kdreiners/HelloExpress/Carthage/Checkouts/Express/Express/Static.swift
    CompileSwift normal x86_64 /Users/kdreiners/HelloExpress/Carthage/Checkouts/Express/Express/ErrorHandler.swift
    CompileSwift normal x86_64 /Users/kdreiners/HelloExpress/Carthage/Checkouts/Express/Express/ExpressSugar.swift
    CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
(5 failures)
/Users/kdreiners/HelloExpress/Carthage/Checkouts/Express/Modules/CPthread/module.map:23:9: error: header '/usr/include/pthread.h' not found
/Users/kdreiners/HelloExpress/Carthage/Checkouts/Express/Express/HttpServer.swift:24:8: error: could not build Objective-C module 'CPThread'
/Users/kdreiners/HelloExpress/Carthage/Checkouts/Express/Modules/CPthread/module.map:23:9: error: header '/usr/include/pthread.h' not found
/Users/kdreiners/HelloExpress/Carthage/Checkouts/Express/Express/HttpServer.swift:24:8: error: could not build Objective-C module 'CPThread'
/Users/kdreiners/HelloExpress/Carthage/Checkouts/Express/Modules/CPthread/module.map:23:9: error: header '/usr/include/pthread.h' not found
/Users/kdreiners/HelloExpress/Carthage/Checkouts/Express/Express/HttpServer.swift:24:8: error: could not build Objective-C module 'CPThread'
/Users/kdreiners/HelloExpress/Carthage/Checkouts/Express/Modules/CPthread/module.map:23:9: error: header '/usr/include/pthread.h' not found
/Users/kdreiners/HelloExpress/Carthage/Checkouts/Express/Express/HttpServer.swift:24:8: error: could not build Objective-C module 'CPThread'
A shell task failed with exit code 65:

Thanks in advance

Best 

Klaus-Dieter

**Comment by dileping** [comment]
Hi @KDReiners!

Thanks a lot for the issue report. Will take a look now and get back to you soon.

Kind Regards,
Daniel

**Comment by dileping** [comment]
@KDReiners,

you should install XCode Command Line tools as it's described in the [Installation](https://github.com/crossroadlabs/Express#installation) section:

``` sh
xcode-select --install
```

I have tried these steps on a clean El Capitain installation and it worked like a charm. Let me know if it worked for you, please.

Thanks,
Daniel

**Comment by KDReiners** [comment]
@dileping 
I took this problem as a trigger for clean install. After that, it worked for me as well. Thank you for your help.
Best

kd

**Comment by dileping** [comment]
@KDReiners, thank you for taking a look at Swift Express and for the feedback! Let us know if you have any other problems.

Stay tuned, we have many new nice features in development.
