### ISSUE TITLE
Failed to discover shared schemes in project MustacheDemoiOS7.xcodeproj

### ISSUE THREAD

**Issue by deapamukchieva** [crossroadlabs/Express#30]
**\* Cloning Box
Failed to discover shared schemes in project MustacheDemoiOS7.xcodeproj—either the project does not have any shared schemes, or xcodebuild never returned

**Comment by dileping** [comment]
@deapamukchieva Thanks for the report. It looks like you are trying to build your app by Carthage and not the Swift Express command line tools.

If you do so, you need to specify a platform you are building for and tell it you need to omit binaries. Something like `carthage bootstrap --platform mac --no-use-binaries`

Let me know if it will work for you, please.
