### ISSUE TITLE
launch path not accessible

### ISSUE THREAD

**Issue by mlabs-jay** [crossroadlabs/Express#32]
I followed the instructions in the readme and `swift-express run` fails.

OS 10.11.4
xcode 7.3

`$ swift-express run
Running cxo-report-generator...
Unhandled error in RunStep. Error: SubtaskError("Task launch error: launch path not accessible")
Subtask Error: Task launch error: launch path not accessible`

**Comment by mlabs-jay** [comment]
looks like this is a known issue https://github.com/crossroadlabs/Express/issues/20

**Comment by mlabs-jay** [comment]
maybe you should mention in the readme that it doesn't work with xcode 7.3/swift 22

**Comment by dileping** [comment]
@mlabs-jay 

Actually it already does work with Xcode 7.3. How could we reproduce it?

Try it with building first: `swift-express bootstrap` and `swift-express build`. Let me know if this one will work for you.

Thanks,
Daniel
