### ISSUE TITLE
SO Question: In Swift Express using Bright Futures, How To Handle Asynchronous Operations?

### ISSUE THREAD

**Issue by christopher-prince** [crossroadlabs/Express#34]
http://stackoverflow.com/questions/38340795/in-swift-express-using-bright-futures-how-to-handle-asynchronous-operations

Thoughts?
Thanks,
Chris.

**Comment by christopher-prince** [comment]
Fixed! See SO post. Thanks!

**Comment by dileping** [comment]
@christopher-prince Cool, thanks! Retagged some other questions with `swiftexpress` tag.
